/**
 * Copyright (c) 2010-2021 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.homematicip.internal.model.common;

/**
 * Homematic IP functional channels
 *
 * @author Nils Sowen (n.sowen@2scale.net)
 * @since 2020-12-24
 */
public enum FunctionalChannelType {
    FUNCTIONAL_CHANNEL,
    ACCELERATION_SENSOR_CHANNEL,
    ACCESS_CONTROLLER_CHANNEL,
    ALARM_SIREN_CHANNEL,
    ANALOG_OUTPUT_CHANNEL,
    ANALOG_ROOM_CONTROL_CHANNEL,
    BLIND_CHANNEL,
    CHANGE_OVER_CHANNEL,
    CONTACT_INTERFACE_CHANNEL,
    CLIMATE_SENSOR_CHANNEL,
    DEHUMIDIFIER_DEMAND_CHANNEL,
    DEVICE_BASE,
    DEVICE_BASE_FLOOR_HEATING,
    DEVICE_GLOBAL_PUMP_CONTROL,
    DEVICE_INCORRECT_POSITIONED,
    DEVICE_OPERATIONLOCK,
    DEVICE_PERMANENT_FULL_RX,
    DEVICE_RECHARGEABLE_WITH_SABOTAGE,
    DEVICE_SABOTAGE,
    DOOR_CHANNEL,
    DIMMER_CHANNEL,
    FLOOR_TERMINAL_BLOCK_CHANNEL,
    FLOOR_TERMINAL_BLOCK_LOCAL_PUMP_CHANNEL,
    FLOOR_TERMINAL_BLOCK_MECHANIC_CHANNEL,
    GENERIC_INPUT_CHANNEL,
    HEAT_DEMAND_CHANNEL,
    HEATING_THERMOSTAT_CHANNEL,
    INTERNAL_SWITCH_CHANNEL,
    LIGHT_SENSOR_CHANNEL,
    MAINS_FAILURE_CHANNEL,
    MOTION_DETECTION_CHANNEL,
    MULTI_MODE_INPUT_CHANNEL,
    MULTI_MODE_INPUT_BLIND_CHANNEL,
    MULTI_MODE_INPUT_SWITCH_CHANNEL,
    NOTIFICATION_LIGHT_CHANNEL,
    PASSAGE_DETECTOR_CHANNEL,
    PRESENCE_DETECTION_CHANNEL,
    ROTARY_HANDLE_CHANNEL,
    SHADING_CHANNEL,
    SHUTTER_CHANNEL,
    SHUTTER_CONTACT_CHANNEL,
    SINGLE_KEY_CHANNEL,
    SMOKE_DETECTOR_CHANNEL,
    SWITCH_CHANNEL,
    SWITCH_MEASURING_CHANNEL,
    TILT_VIBRATION_SENSOR_CHANNEL,
    WALL_MOUNTED_THERMOSTAT_PRO_CHANNEL,
    WALL_MOUNTED_THERMOSTAT_WITHOUT_DISPLAY_CHANNEL,
    WATER_SENSOR_CHANNEL,
    WEATHER_SENSOR_CHANNEL,
    WEATHER_SENSOR_PRO_CHANNEL,
    WEATHER_SENSOR_PLUS_CHANNEL
}
